//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.31 at 12:18:30 PM EST 
//


package com.att.edb.accessquote;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import com.att.cio.commonheader.v3.WSHeader;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://cio.att.com/commonheader/v3}WSHeader"/>
 *         &lt;element name="AccessQuoteAlternateBody">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DQ_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="service" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="accessType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="accessTransport" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="accessBandwidth" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="EGRFlag" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="custAddr1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="custAddr2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="houseNo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="bldgName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="postalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="telephoneCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="freeFormAddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tailTechnology" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="accessInterconnect" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="orderingCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="queryType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="onNetCheck" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="accessArch" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="misPNT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="accesArrangement" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="physicalInterface" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="contractTerm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="userReferenceNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="quoteRequestType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="meetPointIndicator" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="1"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="meetPointVCoordinate" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="50"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="meetPointHCoordinate" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="50"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="iPAGCLLI" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="50"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="connectionType" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="cos" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="CMTU" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="circuitQuantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="discountPercentage" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="lnsClecStrId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "wsHeader",
    "accessQuoteAlternateBody"
})
@XmlRootElement(name = "accessQuoteAlternateRequest")
public class AccessQuoteAlternateRequest {

    @XmlElement(name = "WSHeader", namespace = "http://cio.att.com/commonheader/v3", required = true)
    protected WSHeader wsHeader;
    @XmlElement(name = "AccessQuoteAlternateBody", required = true)
    protected AccessQuoteAlternateRequest.AccessQuoteAlternateBody accessQuoteAlternateBody;

    /**
     * Gets the value of the wsHeader property.
     * 
     * @return
     *     possible object is
     *     {@link WSHeader }
     *     
     */
    public WSHeader getWSHeader() {
        return wsHeader;
    }

    /**
     * Sets the value of the wsHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSHeader }
     *     
     */
    public void setWSHeader(WSHeader value) {
        this.wsHeader = value;
    }

    /**
     * Gets the value of the accessQuoteAlternateBody property.
     * 
     * @return
     *     possible object is
     *     {@link AccessQuoteAlternateRequest.AccessQuoteAlternateBody }
     *     
     */
    public AccessQuoteAlternateRequest.AccessQuoteAlternateBody getAccessQuoteAlternateBody() {
        return accessQuoteAlternateBody;
    }

    /**
     * Sets the value of the accessQuoteAlternateBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessQuoteAlternateRequest.AccessQuoteAlternateBody }
     *     
     */
    public void setAccessQuoteAlternateBody(AccessQuoteAlternateRequest.AccessQuoteAlternateBody value) {
        this.accessQuoteAlternateBody = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DQ_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="service" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="accessType" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="accessTransport" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="accessBandwidth" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="EGRFlag" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="custAddr1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="custAddr2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="houseNo" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="bldgName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="postalCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="telephoneCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="freeFormAddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tailTechnology" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="accessInterconnect" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="orderingCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="queryType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="onNetCheck" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="accessArch" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="misPNT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="accesArrangement" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="physicalInterface" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="contractTerm" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="userReferenceNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="quoteRequestType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="meetPointIndicator" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="1"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="meetPointVCoordinate" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="50"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="meetPointHCoordinate" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="50"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="iPAGCLLI" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="50"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="connectionType" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="cos" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="CMTU" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="circuitQuantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="discountPercentage" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="lnsClecStrId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dqid",
        "country",
        "service",
        "accessType",
        "accessTransport",
        "accessBandwidth",
        "egrFlag",
        "custAddr1",
        "custAddr2",
        "houseNo",
        "bldgName",
        "city",
        "state",
        "postalCode",
        "telephoneCode",
        "freeFormAddr",
        "tailTechnology",
        "accessInterconnect",
        "orderingCode",
        "queryType",
        "onNetCheck",
        "accessArch",
        "misPNT",
        "accesArrangement",
        "physicalInterface",
        "contractTerm",
        "userReferenceNum",
        "quoteRequestType",
        "meetPointIndicator",
        "meetPointVCoordinate",
        "meetPointHCoordinate",
        "ipagclli",
        "connectionType",
        "cos",
        "cmtu",
        "circuitQuantity",
        "discountPercentage",
        "lnsClecStrId"
    })
    public static class AccessQuoteAlternateBody {

        @XmlElement(name = "DQ_ID", required = true)
        protected String dqid;
        @XmlElement(required = true)
        protected String country;
        protected int service;
        protected int accessType;
        protected int accessTransport;
        protected int accessBandwidth;
        @XmlElement(name = "EGRFlag")
        protected int egrFlag;
        @XmlElement(required = true)
        protected String custAddr1;
        @XmlElement(required = true)
        protected String custAddr2;
        protected int houseNo;
        @XmlElement(required = true)
        protected String bldgName;
        @XmlElement(required = true)
        protected String city;
        @XmlElement(required = true)
        protected String state;
        @XmlElement(required = true)
        protected String postalCode;
        @XmlElement(required = true)
        protected String telephoneCode;
        @XmlElement(required = true)
        protected String freeFormAddr;
        protected int tailTechnology;
        protected int accessInterconnect;
        @XmlElement(required = true)
        protected String orderingCode;
        @XmlElement(required = true)
        protected String queryType;
        @XmlElement(required = true)
        protected String onNetCheck;
        @XmlElement(required = true)
        protected String accessArch;
        @XmlElement(required = true)
        protected String misPNT;
        @XmlElement(required = true)
        protected String accesArrangement;
        @XmlElement(required = true)
        protected String physicalInterface;
        @XmlElement(required = true)
        protected String contractTerm;
        @XmlElement(required = true)
        protected String userReferenceNum;
        @XmlElement(required = true)
        protected String quoteRequestType;
        protected String meetPointIndicator;
        protected String meetPointVCoordinate;
        protected String meetPointHCoordinate;
        @XmlElement(name = "iPAGCLLI")
        protected String ipagclli;
        protected Integer connectionType;
        protected Integer cos;
        @XmlElement(name = "CMTU")
        protected Integer cmtu;
        protected String circuitQuantity;
        protected Integer discountPercentage;
        protected String lnsClecStrId;

        /**
         * Gets the value of the dqid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDQID() {
            return dqid;
        }

        /**
         * Sets the value of the dqid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDQID(String value) {
            this.dqid = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountry(String value) {
            this.country = value;
        }

        /**
         * Gets the value of the service property.
         * 
         */
        public int getService() {
            return service;
        }

        /**
         * Sets the value of the service property.
         * 
         */
        public void setService(int value) {
            this.service = value;
        }

        /**
         * Gets the value of the accessType property.
         * 
         */
        public int getAccessType() {
            return accessType;
        }

        /**
         * Sets the value of the accessType property.
         * 
         */
        public void setAccessType(int value) {
            this.accessType = value;
        }

        /**
         * Gets the value of the accessTransport property.
         * 
         */
        public int getAccessTransport() {
            return accessTransport;
        }

        /**
         * Sets the value of the accessTransport property.
         * 
         */
        public void setAccessTransport(int value) {
            this.accessTransport = value;
        }

        /**
         * Gets the value of the accessBandwidth property.
         * 
         */
        public int getAccessBandwidth() {
            return accessBandwidth;
        }

        /**
         * Sets the value of the accessBandwidth property.
         * 
         */
        public void setAccessBandwidth(int value) {
            this.accessBandwidth = value;
        }

        /**
         * Gets the value of the egrFlag property.
         * 
         */
        public int getEGRFlag() {
            return egrFlag;
        }

        /**
         * Sets the value of the egrFlag property.
         * 
         */
        public void setEGRFlag(int value) {
            this.egrFlag = value;
        }

        /**
         * Gets the value of the custAddr1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustAddr1() {
            return custAddr1;
        }

        /**
         * Sets the value of the custAddr1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustAddr1(String value) {
            this.custAddr1 = value;
        }

        /**
         * Gets the value of the custAddr2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustAddr2() {
            return custAddr2;
        }

        /**
         * Sets the value of the custAddr2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustAddr2(String value) {
            this.custAddr2 = value;
        }

        /**
         * Gets the value of the houseNo property.
         * 
         */
        public int getHouseNo() {
            return houseNo;
        }

        /**
         * Sets the value of the houseNo property.
         * 
         */
        public void setHouseNo(int value) {
            this.houseNo = value;
        }

        /**
         * Gets the value of the bldgName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBldgName() {
            return bldgName;
        }

        /**
         * Sets the value of the bldgName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBldgName(String value) {
            this.bldgName = value;
        }

        /**
         * Gets the value of the city property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCity() {
            return city;
        }

        /**
         * Sets the value of the city property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCity(String value) {
            this.city = value;
        }

        /**
         * Gets the value of the state property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getState() {
            return state;
        }

        /**
         * Sets the value of the state property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setState(String value) {
            this.state = value;
        }

        /**
         * Gets the value of the postalCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPostalCode() {
            return postalCode;
        }

        /**
         * Sets the value of the postalCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPostalCode(String value) {
            this.postalCode = value;
        }

        /**
         * Gets the value of the telephoneCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTelephoneCode() {
            return telephoneCode;
        }

        /**
         * Sets the value of the telephoneCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTelephoneCode(String value) {
            this.telephoneCode = value;
        }

        /**
         * Gets the value of the freeFormAddr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFreeFormAddr() {
            return freeFormAddr;
        }

        /**
         * Sets the value of the freeFormAddr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFreeFormAddr(String value) {
            this.freeFormAddr = value;
        }

        /**
         * Gets the value of the tailTechnology property.
         * 
         */
        public int getTailTechnology() {
            return tailTechnology;
        }

        /**
         * Sets the value of the tailTechnology property.
         * 
         */
        public void setTailTechnology(int value) {
            this.tailTechnology = value;
        }

        /**
         * Gets the value of the accessInterconnect property.
         * 
         */
        public int getAccessInterconnect() {
            return accessInterconnect;
        }

        /**
         * Sets the value of the accessInterconnect property.
         * 
         */
        public void setAccessInterconnect(int value) {
            this.accessInterconnect = value;
        }

        /**
         * Gets the value of the orderingCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderingCode() {
            return orderingCode;
        }

        /**
         * Sets the value of the orderingCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderingCode(String value) {
            this.orderingCode = value;
        }

        /**
         * Gets the value of the queryType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQueryType() {
            return queryType;
        }

        /**
         * Sets the value of the queryType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQueryType(String value) {
            this.queryType = value;
        }

        /**
         * Gets the value of the onNetCheck property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOnNetCheck() {
            return onNetCheck;
        }

        /**
         * Sets the value of the onNetCheck property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOnNetCheck(String value) {
            this.onNetCheck = value;
        }

        /**
         * Gets the value of the accessArch property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccessArch() {
            return accessArch;
        }

        /**
         * Sets the value of the accessArch property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccessArch(String value) {
            this.accessArch = value;
        }

        /**
         * Gets the value of the misPNT property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMisPNT() {
            return misPNT;
        }

        /**
         * Sets the value of the misPNT property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMisPNT(String value) {
            this.misPNT = value;
        }

        /**
         * Gets the value of the accesArrangement property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccesArrangement() {
            return accesArrangement;
        }

        /**
         * Sets the value of the accesArrangement property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccesArrangement(String value) {
            this.accesArrangement = value;
        }

        /**
         * Gets the value of the physicalInterface property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhysicalInterface() {
            return physicalInterface;
        }

        /**
         * Sets the value of the physicalInterface property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhysicalInterface(String value) {
            this.physicalInterface = value;
        }

        /**
         * Gets the value of the contractTerm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContractTerm() {
            return contractTerm;
        }

        /**
         * Sets the value of the contractTerm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContractTerm(String value) {
            this.contractTerm = value;
        }

        /**
         * Gets the value of the userReferenceNum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUserReferenceNum() {
            return userReferenceNum;
        }

        /**
         * Sets the value of the userReferenceNum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUserReferenceNum(String value) {
            this.userReferenceNum = value;
        }

        /**
         * Gets the value of the quoteRequestType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getQuoteRequestType() {
            return quoteRequestType;
        }

        /**
         * Sets the value of the quoteRequestType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setQuoteRequestType(String value) {
            this.quoteRequestType = value;
        }

        /**
         * Gets the value of the meetPointIndicator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMeetPointIndicator() {
            return meetPointIndicator;
        }

        /**
         * Sets the value of the meetPointIndicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMeetPointIndicator(String value) {
            this.meetPointIndicator = value;
        }

        /**
         * Gets the value of the meetPointVCoordinate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMeetPointVCoordinate() {
            return meetPointVCoordinate;
        }

        /**
         * Sets the value of the meetPointVCoordinate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMeetPointVCoordinate(String value) {
            this.meetPointVCoordinate = value;
        }

        /**
         * Gets the value of the meetPointHCoordinate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMeetPointHCoordinate() {
            return meetPointHCoordinate;
        }

        /**
         * Sets the value of the meetPointHCoordinate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMeetPointHCoordinate(String value) {
            this.meetPointHCoordinate = value;
        }

        /**
         * Gets the value of the ipagclli property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIPAGCLLI() {
            return ipagclli;
        }

        /**
         * Sets the value of the ipagclli property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIPAGCLLI(String value) {
            this.ipagclli = value;
        }

        /**
         * Gets the value of the connectionType property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getConnectionType() {
            return connectionType;
        }

        /**
         * Sets the value of the connectionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setConnectionType(Integer value) {
            this.connectionType = value;
        }

        /**
         * Gets the value of the cos property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getCos() {
            return cos;
        }

        /**
         * Sets the value of the cos property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setCos(Integer value) {
            this.cos = value;
        }

        /**
         * Gets the value of the cmtu property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getCMTU() {
            return cmtu;
        }

        /**
         * Sets the value of the cmtu property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setCMTU(Integer value) {
            this.cmtu = value;
        }

        /**
         * Gets the value of the circuitQuantity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCircuitQuantity() {
            return circuitQuantity;
        }

        /**
         * Sets the value of the circuitQuantity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCircuitQuantity(String value) {
            this.circuitQuantity = value;
        }

        /**
         * Gets the value of the discountPercentage property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getDiscountPercentage() {
            return discountPercentage;
        }

        /**
         * Sets the value of the discountPercentage property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setDiscountPercentage(Integer value) {
            this.discountPercentage = value;
        }

        /**
         * Gets the value of the lnsClecStrId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLnsClecStrId() {
            return lnsClecStrId;
        }

        /**
         * Sets the value of the lnsClecStrId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLnsClecStrId(String value) {
            this.lnsClecStrId = value;
        }

    }

}
