//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.31 at 12:18:30 PM EST 
//


package com.att.edb.accessquote;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import com.att.cio.commonheader.v3.WSResponseHeader;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://cio.att.com/commonheader/v3}WSResponseHeader"/>
 *         &lt;element name="AccessQuoteAlternateBody">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="EGRFlag" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="cityURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Customer_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Cust_addr1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Cust_addr2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Cust_city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Cust_postalcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Cust_state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="geoAddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="matchStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="matchScore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="matchLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Cust_country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Cust_telephone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Speed" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Service" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tokenID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="onNetCheck" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="accessArch" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="availability" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="misPNT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="accessArrangement" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ethernetIOC" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="accessSupplierList">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="AccessSupplier" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ITUCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="supplierName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="supplierTier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="leadTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="PMTU" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="mtuSupportMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element ref="{http://edb.att.com/accessQuote}altNodeList"/>
 *                                       &lt;element ref="{http://edb.att.com/accessQuote}altInterfaceList"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="meetPointIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="meetPointVCoordinate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="meetPointHCoordinate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="iPAGCLLI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="connectionType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="cos" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="serviceGuideEligibleIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="discountPercentage" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="quoteRequestDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *                   &lt;element name="CMTU" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="circuitQuantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "wsResponseHeader",
    "accessQuoteAlternateBody"
})
@XmlRootElement(name = "accessQuoteAlternateResponse")
public class AccessQuoteAlternateResponse {

    @XmlElement(name = "WSResponseHeader", namespace = "http://cio.att.com/commonheader/v3", required = true)
    protected WSResponseHeader wsResponseHeader;
    @XmlElement(name = "AccessQuoteAlternateBody", required = true)
    protected AccessQuoteAlternateResponse.AccessQuoteAlternateBody accessQuoteAlternateBody;

    /**
     * Gets the value of the wsResponseHeader property.
     * 
     * @return
     *     possible object is
     *     {@link WSResponseHeader }
     *     
     */
    public WSResponseHeader getWSResponseHeader() {
        return wsResponseHeader;
    }

    /**
     * Sets the value of the wsResponseHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSResponseHeader }
     *     
     */
    public void setWSResponseHeader(WSResponseHeader value) {
        this.wsResponseHeader = value;
    }

    /**
     * Gets the value of the accessQuoteAlternateBody property.
     * 
     * @return
     *     possible object is
     *     {@link AccessQuoteAlternateResponse.AccessQuoteAlternateBody }
     *     
     */
    public AccessQuoteAlternateResponse.AccessQuoteAlternateBody getAccessQuoteAlternateBody() {
        return accessQuoteAlternateBody;
    }

    /**
     * Sets the value of the accessQuoteAlternateBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessQuoteAlternateResponse.AccessQuoteAlternateBody }
     *     
     */
    public void setAccessQuoteAlternateBody(AccessQuoteAlternateResponse.AccessQuoteAlternateBody value) {
        this.accessQuoteAlternateBody = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="EGRFlag" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="URL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="cityURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Customer_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Cust_addr1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Cust_addr2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Cust_city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Cust_postalcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Cust_state" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="geoAddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="latitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="longitude" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="matchStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="matchScore" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="matchLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Cust_country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Cust_telephone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Speed" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Service" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="tokenID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="onNetCheck" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="accessArch" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="availability" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="misPNT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="accessArrangement" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ethernetIOC" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="accessSupplierList">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="AccessSupplier" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ITUCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="supplierName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="supplierTier" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="leadTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="PMTU" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="mtuSupportMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element ref="{http://edb.att.com/accessQuote}altNodeList"/>
     *                             &lt;element ref="{http://edb.att.com/accessQuote}altInterfaceList"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="meetPointIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="meetPointVCoordinate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="meetPointHCoordinate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="iPAGCLLI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="connectionType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="cos" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="serviceGuideEligibleIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="discountPercentage" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="quoteRequestDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
     *         &lt;element name="CMTU" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="circuitQuantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "egrFlag",
        "url",
        "cityURL",
        "customerName",
        "custAddr1",
        "custAddr2",
        "custCity",
        "custPostalcode",
        "custState",
        "geoAddr",
        "latitude",
        "longitude",
        "matchStatus",
        "matchScore",
        "matchLevel",
        "custCountry",
        "custTelephone",
        "speed",
        "service",
        "tokenID",
        "onNetCheck",
        "accessArch",
        "availability",
        "misPNT",
        "accessArrangement",
        "ethernetIOC",
        "accessSupplierList",
        "meetPointIndicator",
        "meetPointVCoordinate",
        "meetPointHCoordinate",
        "ipagclli",
        "connectionType",
        "cos",
        "serviceGuideEligibleIndicator",
        "discountPercentage",
        "quoteRequestDate",
        "cmtu",
        "circuitQuantity"
    })
    public static class AccessQuoteAlternateBody {

        @XmlElement(name = "EGRFlag")
        protected int egrFlag;
        @XmlElement(name = "URL", required = true)
        protected String url;
        @XmlElement(required = true)
        protected String cityURL;
        @XmlElement(name = "Customer_name", required = true)
        protected String customerName;
        @XmlElement(name = "Cust_addr1", required = true)
        protected String custAddr1;
        @XmlElement(name = "Cust_addr2", required = true)
        protected String custAddr2;
        @XmlElement(name = "Cust_city", required = true)
        protected String custCity;
        @XmlElement(name = "Cust_postalcode", required = true)
        protected String custPostalcode;
        @XmlElement(name = "Cust_state", required = true)
        protected String custState;
        @XmlElement(required = true)
        protected String geoAddr;
        @XmlElement(required = true)
        protected BigDecimal latitude;
        @XmlElement(required = true)
        protected BigDecimal longitude;
        @XmlElement(required = true)
        protected String matchStatus;
        @XmlElement(required = true)
        protected String matchScore;
        @XmlElement(required = true)
        protected String matchLevel;
        @XmlElement(name = "Cust_country", required = true)
        protected String custCountry;
        @XmlElement(name = "Cust_telephone", required = true)
        protected String custTelephone;
        @XmlElement(name = "Speed", required = true)
        protected String speed;
        @XmlElement(name = "Service", required = true)
        protected String service;
        @XmlElement(required = true)
        protected String tokenID;
        @XmlElement(required = true)
        protected String onNetCheck;
        @XmlElement(required = true)
        protected String accessArch;
        @XmlElement(required = true)
        protected String availability;
        @XmlElement(required = true)
        protected String misPNT;
        @XmlElement(required = true)
        protected String accessArrangement;
        @XmlElement(required = true)
        protected String ethernetIOC;
        @XmlElement(required = true)
        protected AccessQuoteAlternateResponse.AccessQuoteAlternateBody.AccessSupplierList accessSupplierList;
        protected String meetPointIndicator;
        protected String meetPointVCoordinate;
        protected String meetPointHCoordinate;
        @XmlElement(name = "iPAGCLLI")
        protected String ipagclli;
        protected String connectionType;
        protected String cos;
        protected String serviceGuideEligibleIndicator;
        protected Integer discountPercentage;
        protected XMLGregorianCalendar quoteRequestDate;
        @XmlElement(name = "CMTU")
        protected Integer cmtu;
        protected String circuitQuantity;

        /**
         * Gets the value of the egrFlag property.
         * 
         */
        public int getEGRFlag() {
            return egrFlag;
        }

        /**
         * Sets the value of the egrFlag property.
         * 
         */
        public void setEGRFlag(int value) {
            this.egrFlag = value;
        }

        /**
         * Gets the value of the url property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getURL() {
            return url;
        }

        /**
         * Sets the value of the url property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setURL(String value) {
            this.url = value;
        }

        /**
         * Gets the value of the cityURL property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCityURL() {
            return cityURL;
        }

        /**
         * Sets the value of the cityURL property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCityURL(String value) {
            this.cityURL = value;
        }

        /**
         * Gets the value of the customerName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustomerName() {
            return customerName;
        }

        /**
         * Sets the value of the customerName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustomerName(String value) {
            this.customerName = value;
        }

        /**
         * Gets the value of the custAddr1 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustAddr1() {
            return custAddr1;
        }

        /**
         * Sets the value of the custAddr1 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustAddr1(String value) {
            this.custAddr1 = value;
        }

        /**
         * Gets the value of the custAddr2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustAddr2() {
            return custAddr2;
        }

        /**
         * Sets the value of the custAddr2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustAddr2(String value) {
            this.custAddr2 = value;
        }

        /**
         * Gets the value of the custCity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustCity() {
            return custCity;
        }

        /**
         * Sets the value of the custCity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustCity(String value) {
            this.custCity = value;
        }

        /**
         * Gets the value of the custPostalcode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustPostalcode() {
            return custPostalcode;
        }

        /**
         * Sets the value of the custPostalcode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustPostalcode(String value) {
            this.custPostalcode = value;
        }

        /**
         * Gets the value of the custState property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustState() {
            return custState;
        }

        /**
         * Sets the value of the custState property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustState(String value) {
            this.custState = value;
        }

        /**
         * Gets the value of the geoAddr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGeoAddr() {
            return geoAddr;
        }

        /**
         * Sets the value of the geoAddr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGeoAddr(String value) {
            this.geoAddr = value;
        }

        /**
         * Gets the value of the latitude property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getLatitude() {
            return latitude;
        }

        /**
         * Sets the value of the latitude property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setLatitude(BigDecimal value) {
            this.latitude = value;
        }

        /**
         * Gets the value of the longitude property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getLongitude() {
            return longitude;
        }

        /**
         * Sets the value of the longitude property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setLongitude(BigDecimal value) {
            this.longitude = value;
        }

        /**
         * Gets the value of the matchStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMatchStatus() {
            return matchStatus;
        }

        /**
         * Sets the value of the matchStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMatchStatus(String value) {
            this.matchStatus = value;
        }

        /**
         * Gets the value of the matchScore property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMatchScore() {
            return matchScore;
        }

        /**
         * Sets the value of the matchScore property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMatchScore(String value) {
            this.matchScore = value;
        }

        /**
         * Gets the value of the matchLevel property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMatchLevel() {
            return matchLevel;
        }

        /**
         * Sets the value of the matchLevel property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMatchLevel(String value) {
            this.matchLevel = value;
        }

        /**
         * Gets the value of the custCountry property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustCountry() {
            return custCountry;
        }

        /**
         * Sets the value of the custCountry property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustCountry(String value) {
            this.custCountry = value;
        }

        /**
         * Gets the value of the custTelephone property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCustTelephone() {
            return custTelephone;
        }

        /**
         * Sets the value of the custTelephone property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCustTelephone(String value) {
            this.custTelephone = value;
        }

        /**
         * Gets the value of the speed property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpeed() {
            return speed;
        }

        /**
         * Sets the value of the speed property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpeed(String value) {
            this.speed = value;
        }

        /**
         * Gets the value of the service property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getService() {
            return service;
        }

        /**
         * Sets the value of the service property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setService(String value) {
            this.service = value;
        }

        /**
         * Gets the value of the tokenID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTokenID() {
            return tokenID;
        }

        /**
         * Sets the value of the tokenID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTokenID(String value) {
            this.tokenID = value;
        }

        /**
         * Gets the value of the onNetCheck property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOnNetCheck() {
            return onNetCheck;
        }

        /**
         * Sets the value of the onNetCheck property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOnNetCheck(String value) {
            this.onNetCheck = value;
        }

        /**
         * Gets the value of the accessArch property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccessArch() {
            return accessArch;
        }

        /**
         * Sets the value of the accessArch property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccessArch(String value) {
            this.accessArch = value;
        }

        /**
         * Gets the value of the availability property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAvailability() {
            return availability;
        }

        /**
         * Sets the value of the availability property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAvailability(String value) {
            this.availability = value;
        }

        /**
         * Gets the value of the misPNT property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMisPNT() {
            return misPNT;
        }

        /**
         * Sets the value of the misPNT property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMisPNT(String value) {
            this.misPNT = value;
        }

        /**
         * Gets the value of the accessArrangement property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccessArrangement() {
            return accessArrangement;
        }

        /**
         * Sets the value of the accessArrangement property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccessArrangement(String value) {
            this.accessArrangement = value;
        }

        /**
         * Gets the value of the ethernetIOC property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEthernetIOC() {
            return ethernetIOC;
        }

        /**
         * Sets the value of the ethernetIOC property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEthernetIOC(String value) {
            this.ethernetIOC = value;
        }

        /**
         * Gets the value of the accessSupplierList property.
         * 
         * @return
         *     possible object is
         *     {@link AccessQuoteAlternateResponse.AccessQuoteAlternateBody.AccessSupplierList }
         *     
         */
        public AccessQuoteAlternateResponse.AccessQuoteAlternateBody.AccessSupplierList getAccessSupplierList() {
            return accessSupplierList;
        }

        /**
         * Sets the value of the accessSupplierList property.
         * 
         * @param value
         *     allowed object is
         *     {@link AccessQuoteAlternateResponse.AccessQuoteAlternateBody.AccessSupplierList }
         *     
         */
        public void setAccessSupplierList(AccessQuoteAlternateResponse.AccessQuoteAlternateBody.AccessSupplierList value) {
            this.accessSupplierList = value;
        }

        /**
         * Gets the value of the meetPointIndicator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMeetPointIndicator() {
            return meetPointIndicator;
        }

        /**
         * Sets the value of the meetPointIndicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMeetPointIndicator(String value) {
            this.meetPointIndicator = value;
        }

        /**
         * Gets the value of the meetPointVCoordinate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMeetPointVCoordinate() {
            return meetPointVCoordinate;
        }

        /**
         * Sets the value of the meetPointVCoordinate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMeetPointVCoordinate(String value) {
            this.meetPointVCoordinate = value;
        }

        /**
         * Gets the value of the meetPointHCoordinate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMeetPointHCoordinate() {
            return meetPointHCoordinate;
        }

        /**
         * Sets the value of the meetPointHCoordinate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMeetPointHCoordinate(String value) {
            this.meetPointHCoordinate = value;
        }

        /**
         * Gets the value of the ipagclli property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIPAGCLLI() {
            return ipagclli;
        }

        /**
         * Sets the value of the ipagclli property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIPAGCLLI(String value) {
            this.ipagclli = value;
        }

        /**
         * Gets the value of the connectionType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getConnectionType() {
            return connectionType;
        }

        /**
         * Sets the value of the connectionType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setConnectionType(String value) {
            this.connectionType = value;
        }

        /**
         * Gets the value of the cos property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCos() {
            return cos;
        }

        /**
         * Sets the value of the cos property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCos(String value) {
            this.cos = value;
        }

        /**
         * Gets the value of the serviceGuideEligibleIndicator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getServiceGuideEligibleIndicator() {
            return serviceGuideEligibleIndicator;
        }

        /**
         * Sets the value of the serviceGuideEligibleIndicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setServiceGuideEligibleIndicator(String value) {
            this.serviceGuideEligibleIndicator = value;
        }

        /**
         * Gets the value of the discountPercentage property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getDiscountPercentage() {
            return discountPercentage;
        }

        /**
         * Sets the value of the discountPercentage property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setDiscountPercentage(Integer value) {
            this.discountPercentage = value;
        }

        /**
         * Gets the value of the quoteRequestDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getQuoteRequestDate() {
            return quoteRequestDate;
        }

        /**
         * Sets the value of the quoteRequestDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setQuoteRequestDate(XMLGregorianCalendar value) {
            this.quoteRequestDate = value;
        }

        /**
         * Gets the value of the cmtu property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getCMTU() {
            return cmtu;
        }

        /**
         * Sets the value of the cmtu property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setCMTU(Integer value) {
            this.cmtu = value;
        }

        /**
         * Gets the value of the circuitQuantity property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCircuitQuantity() {
            return circuitQuantity;
        }

        /**
         * Sets the value of the circuitQuantity property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCircuitQuantity(String value) {
            this.circuitQuantity = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="AccessSupplier" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ITUCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="supplierName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="supplierTier" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="leadTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="PMTU" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="mtuSupportMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element ref="{http://edb.att.com/accessQuote}altNodeList"/>
         *                   &lt;element ref="{http://edb.att.com/accessQuote}altInterfaceList"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "accessSupplier"
        })
        public static class AccessSupplierList {

            @XmlElement(name = "AccessSupplier")
            protected List<AccessQuoteAlternateResponse.AccessQuoteAlternateBody.AccessSupplierList.AccessSupplier> accessSupplier;

            /**
             * Gets the value of the accessSupplier property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the accessSupplier property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAccessSupplier().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link AccessQuoteAlternateResponse.AccessQuoteAlternateBody.AccessSupplierList.AccessSupplier }
             * 
             * 
             */
            public List<AccessQuoteAlternateResponse.AccessQuoteAlternateBody.AccessSupplierList.AccessSupplier> getAccessSupplier() {
                if (accessSupplier == null) {
                    accessSupplier = new ArrayList<AccessQuoteAlternateResponse.AccessQuoteAlternateBody.AccessSupplierList.AccessSupplier>();
                }
                return this.accessSupplier;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ITUCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="supplierName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="supplierTier" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="leadTime" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="PMTU" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="mtuSupportMessage" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element ref="{http://edb.att.com/accessQuote}altNodeList"/>
             *         &lt;element ref="{http://edb.att.com/accessQuote}altInterfaceList"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "ituCode",
                "supplierName",
                "supplierTier",
                "leadTime",
                "pmtu",
                "mtuSupportMessage",
                "altNodeList",
                "altInterfaceList"
            })
            public static class AccessSupplier {

                @XmlElement(name = "ITUCode", required = true)
                protected String ituCode;
                @XmlElement(required = true)
                protected String supplierName;
                @XmlElement(required = true)
                protected String supplierTier;
                protected int leadTime;
                @XmlElement(name = "PMTU", required = true)
                protected String pmtu;
                @XmlElement(required = true)
                protected String mtuSupportMessage;
                @XmlElement(required = true)
                protected AltNodeList altNodeList;
                @XmlElement(required = true)
                protected AltInterfaceList altInterfaceList;

                /**
                 * Gets the value of the ituCode property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getITUCode() {
                    return ituCode;
                }

                /**
                 * Sets the value of the ituCode property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setITUCode(String value) {
                    this.ituCode = value;
                }

                /**
                 * Gets the value of the supplierName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSupplierName() {
                    return supplierName;
                }

                /**
                 * Sets the value of the supplierName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSupplierName(String value) {
                    this.supplierName = value;
                }

                /**
                 * Gets the value of the supplierTier property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSupplierTier() {
                    return supplierTier;
                }

                /**
                 * Sets the value of the supplierTier property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSupplierTier(String value) {
                    this.supplierTier = value;
                }

                /**
                 * Gets the value of the leadTime property.
                 * 
                 */
                public int getLeadTime() {
                    return leadTime;
                }

                /**
                 * Sets the value of the leadTime property.
                 * 
                 */
                public void setLeadTime(int value) {
                    this.leadTime = value;
                }

                /**
                 * Gets the value of the pmtu property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPMTU() {
                    return pmtu;
                }

                /**
                 * Sets the value of the pmtu property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPMTU(String value) {
                    this.pmtu = value;
                }

                /**
                 * Gets the value of the mtuSupportMessage property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMtuSupportMessage() {
                    return mtuSupportMessage;
                }

                /**
                 * Sets the value of the mtuSupportMessage property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMtuSupportMessage(String value) {
                    this.mtuSupportMessage = value;
                }

                /**
                 * Gets the value of the altNodeList property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link AltNodeList }
                 *     
                 */
                public AltNodeList getAltNodeList() {
                    return altNodeList;
                }

                /**
                 * Sets the value of the altNodeList property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link AltNodeList }
                 *     
                 */
                public void setAltNodeList(AltNodeList value) {
                    this.altNodeList = value;
                }

                /**
                 * Gets the value of the altInterfaceList property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link AltInterfaceList }
                 *     
                 */
                public AltInterfaceList getAltInterfaceList() {
                    return altInterfaceList;
                }

                /**
                 * Sets the value of the altInterfaceList property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link AltInterfaceList }
                 *     
                 */
                public void setAltInterfaceList(AltInterfaceList value) {
                    this.altInterfaceList = value;
                }

            }

        }

    }

}
