//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.30 at 06:15:54 PM EST 
//


package com.att.edb.accessquote;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="contractTermObj" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="contractTerm" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="baseMonthlyPriceLocal" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                   &lt;element name="monthlyPriceLocal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="oneTimePriceLocal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="baseMonthlyPriceUSD" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                   &lt;element name="monthlyPriceUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="oneTimePriceUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="baseMACCarrierCurrency" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="baseOTICarrierCurrency" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="baseOTCCarrierCurrency" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="carrierQuotedCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="markupPercentMAC" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="markupPercentOTI" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="markupPercentOTC" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "contractTermObj"
})
@XmlRootElement(name = "altContractTermList")
public class AltContractTermList {

    protected List<AltContractTermList.ContractTermObj> contractTermObj;

    /**
     * Gets the value of the contractTermObj property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contractTermObj property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContractTermObj().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AltContractTermList.ContractTermObj }
     * 
     * 
     */
    public List<AltContractTermList.ContractTermObj> getContractTermObj() {
        if (contractTermObj == null) {
            contractTermObj = new ArrayList<AltContractTermList.ContractTermObj>();
        }
        return this.contractTermObj;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="contractTerm" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="baseMonthlyPriceLocal" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *         &lt;element name="monthlyPriceLocal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="oneTimePriceLocal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="baseMonthlyPriceUSD" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *         &lt;element name="monthlyPriceUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="oneTimePriceUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="baseMACCarrierCurrency" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="baseOTICarrierCurrency" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="baseOTCCarrierCurrency" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="carrierQuotedCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="markupPercentMAC" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="markupPercentOTI" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="markupPercentOTC" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "contractTerm",
        "baseMonthlyPriceLocal",
        "monthlyPriceLocal",
        "oneTimePriceLocal",
        "baseMonthlyPriceUSD",
        "monthlyPriceUSD",
        "oneTimePriceUSD",
        "baseMACCarrierCurrency",
        "baseOTICarrierCurrency",
        "baseOTCCarrierCurrency",
        "carrierQuotedCurrency",
        "markupPercentMAC",
        "markupPercentOTI",
        "markupPercentOTC"
    })
    public static class ContractTermObj {

        @XmlElement(required = true)
        protected String contractTerm;
        protected BigDecimal baseMonthlyPriceLocal;
        @XmlElement(required = true)
        protected BigDecimal monthlyPriceLocal;
        @XmlElement(required = true)
        protected BigDecimal oneTimePriceLocal;
        protected BigDecimal baseMonthlyPriceUSD;
        @XmlElement(required = true)
        protected BigDecimal monthlyPriceUSD;
        @XmlElement(required = true)
        protected BigDecimal oneTimePriceUSD;
        @XmlElement(required = true)
        protected BigDecimal baseMACCarrierCurrency;
        @XmlElement(required = true)
        protected BigDecimal baseOTICarrierCurrency;
        @XmlElement(required = true)
        protected BigDecimal baseOTCCarrierCurrency;
        @XmlElement(required = true)
        protected String carrierQuotedCurrency;
        @XmlElement(required = true)
        protected BigDecimal markupPercentMAC;
        @XmlElement(required = true)
        protected BigDecimal markupPercentOTI;
        @XmlElement(required = true)
        protected BigDecimal markupPercentOTC;

        /**
         * Gets the value of the contractTerm property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContractTerm() {
            return contractTerm;
        }

        /**
         * Sets the value of the contractTerm property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContractTerm(String value) {
            this.contractTerm = value;
        }

        /**
         * Gets the value of the baseMonthlyPriceLocal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getBaseMonthlyPriceLocal() {
            return baseMonthlyPriceLocal;
        }

        /**
         * Sets the value of the baseMonthlyPriceLocal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setBaseMonthlyPriceLocal(BigDecimal value) {
            this.baseMonthlyPriceLocal = value;
        }

        /**
         * Gets the value of the monthlyPriceLocal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMonthlyPriceLocal() {
            return monthlyPriceLocal;
        }

        /**
         * Sets the value of the monthlyPriceLocal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMonthlyPriceLocal(BigDecimal value) {
            this.monthlyPriceLocal = value;
        }

        /**
         * Gets the value of the oneTimePriceLocal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getOneTimePriceLocal() {
            return oneTimePriceLocal;
        }

        /**
         * Sets the value of the oneTimePriceLocal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setOneTimePriceLocal(BigDecimal value) {
            this.oneTimePriceLocal = value;
        }

        /**
         * Gets the value of the baseMonthlyPriceUSD property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getBaseMonthlyPriceUSD() {
            return baseMonthlyPriceUSD;
        }

        /**
         * Sets the value of the baseMonthlyPriceUSD property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setBaseMonthlyPriceUSD(BigDecimal value) {
            this.baseMonthlyPriceUSD = value;
        }

        /**
         * Gets the value of the monthlyPriceUSD property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMonthlyPriceUSD() {
            return monthlyPriceUSD;
        }

        /**
         * Sets the value of the monthlyPriceUSD property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMonthlyPriceUSD(BigDecimal value) {
            this.monthlyPriceUSD = value;
        }

        /**
         * Gets the value of the oneTimePriceUSD property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getOneTimePriceUSD() {
            return oneTimePriceUSD;
        }

        /**
         * Sets the value of the oneTimePriceUSD property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setOneTimePriceUSD(BigDecimal value) {
            this.oneTimePriceUSD = value;
        }

        /**
         * Gets the value of the baseMACCarrierCurrency property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getBaseMACCarrierCurrency() {
            return baseMACCarrierCurrency;
        }

        /**
         * Sets the value of the baseMACCarrierCurrency property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setBaseMACCarrierCurrency(BigDecimal value) {
            this.baseMACCarrierCurrency = value;
        }

        /**
         * Gets the value of the baseOTICarrierCurrency property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getBaseOTICarrierCurrency() {
            return baseOTICarrierCurrency;
        }

        /**
         * Sets the value of the baseOTICarrierCurrency property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setBaseOTICarrierCurrency(BigDecimal value) {
            this.baseOTICarrierCurrency = value;
        }

        /**
         * Gets the value of the baseOTCCarrierCurrency property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getBaseOTCCarrierCurrency() {
            return baseOTCCarrierCurrency;
        }

        /**
         * Sets the value of the baseOTCCarrierCurrency property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setBaseOTCCarrierCurrency(BigDecimal value) {
            this.baseOTCCarrierCurrency = value;
        }

        /**
         * Gets the value of the carrierQuotedCurrency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCarrierQuotedCurrency() {
            return carrierQuotedCurrency;
        }

        /**
         * Sets the value of the carrierQuotedCurrency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCarrierQuotedCurrency(String value) {
            this.carrierQuotedCurrency = value;
        }

        /**
         * Gets the value of the markupPercentMAC property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMarkupPercentMAC() {
            return markupPercentMAC;
        }

        /**
         * Sets the value of the markupPercentMAC property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMarkupPercentMAC(BigDecimal value) {
            this.markupPercentMAC = value;
        }

        /**
         * Gets the value of the markupPercentOTI property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMarkupPercentOTI() {
            return markupPercentOTI;
        }

        /**
         * Sets the value of the markupPercentOTI property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMarkupPercentOTI(BigDecimal value) {
            this.markupPercentOTI = value;
        }

        /**
         * Gets the value of the markupPercentOTC property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMarkupPercentOTC() {
            return markupPercentOTC;
        }

        /**
         * Sets the value of the markupPercentOTC property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMarkupPercentOTC(BigDecimal value) {
            this.markupPercentOTC = value;
        }

    }

}
