//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.31 at 12:18:30 PM EST 
//


package com.att.edb.accessquote;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="interfaceObj" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="electricalInterface" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="physicalConnector" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="impedance" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="physicalInterface" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "interfaceObj"
})
@XmlRootElement(name = "altInterfaceList")
public class AltInterfaceList {

    protected List<AltInterfaceList.InterfaceObj> interfaceObj;

    /**
     * Gets the value of the interfaceObj property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interfaceObj property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterfaceObj().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AltInterfaceList.InterfaceObj }
     * 
     * 
     */
    public List<AltInterfaceList.InterfaceObj> getInterfaceObj() {
        if (interfaceObj == null) {
            interfaceObj = new ArrayList<AltInterfaceList.InterfaceObj>();
        }
        return this.interfaceObj;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="electricalInterface" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="physicalConnector" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="impedance" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="physicalInterface" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "electricalInterface",
        "physicalConnector",
        "impedance",
        "physicalInterface"
    })
    public static class InterfaceObj {

        protected int electricalInterface;
        protected int physicalConnector;
        protected int impedance;
        @XmlElement(required = true)
        protected String physicalInterface;

        /**
         * Gets the value of the electricalInterface property.
         * 
         */
        public int getElectricalInterface() {
            return electricalInterface;
        }

        /**
         * Sets the value of the electricalInterface property.
         * 
         */
        public void setElectricalInterface(int value) {
            this.electricalInterface = value;
        }

        /**
         * Gets the value of the physicalConnector property.
         * 
         */
        public int getPhysicalConnector() {
            return physicalConnector;
        }

        /**
         * Sets the value of the physicalConnector property.
         * 
         */
        public void setPhysicalConnector(int value) {
            this.physicalConnector = value;
        }

        /**
         * Gets the value of the impedance property.
         * 
         */
        public int getImpedance() {
            return impedance;
        }

        /**
         * Sets the value of the impedance property.
         * 
         */
        public void setImpedance(int value) {
            this.impedance = value;
        }

        /**
         * Gets the value of the physicalInterface property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPhysicalInterface() {
            return physicalInterface;
        }

        /**
         * Sets the value of the physicalInterface property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPhysicalInterface(String value) {
            this.physicalInterface = value;
        }

    }

}
