//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.31 at 11:55:55 AM EST 
//


package com.att.edb.accessquote;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://edb.att.com/accessQuote}accessQuoteRequest"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accessQuoteRequest"
})
@XmlRootElement(name = "getAccessQuote")
public class GetAccessQuote {

    @XmlElement(required = true)
    protected AccessQuoteRequest accessQuoteRequest;

    /**
     * Gets the value of the accessQuoteRequest property.
     * 
     * @return
     *     possible object is
     *     {@link AccessQuoteRequest }
     *     
     */
    public AccessQuoteRequest getAccessQuoteRequest() {
        return accessQuoteRequest;
    }

    /**
     * Sets the value of the accessQuoteRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessQuoteRequest }
     *     
     */
    public void setAccessQuoteRequest(AccessQuoteRequest value) {
        this.accessQuoteRequest = value;
    }

}
