//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.31 at 12:18:30 PM EST 
//


package com.att.edb.accessquote;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://edb.att.com/accessQuote}accessQuoteResponse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "accessQuoteResponse"
})
@XmlRootElement(name = "getAccessQuoteResponse")
public class GetAccessQuoteResponse {

    @XmlElement(required = true)
    protected AccessQuoteResponse accessQuoteResponse;

    /**
     * Gets the value of the accessQuoteResponse property.
     * 
     * @return
     *     possible object is
     *     {@link AccessQuoteResponse }
     *     
     */
    public AccessQuoteResponse getAccessQuoteResponse() {
        return accessQuoteResponse;
    }

    /**
     * Sets the value of the accessQuoteResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessQuoteResponse }
     *     
     */
    public void setAccessQuoteResponse(AccessQuoteResponse value) {
        this.accessQuoteResponse = value;
    }

}
