//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.31 at 11:55:55 AM EST 
//


package com.att.edb.accessquote;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nodeObj" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nodeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="CLLI" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="signalType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element ref="{http://edb.att.com/accessQuote}contractTermList"/>
 *                   &lt;element name="monthlyCostLocal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="oneTimeCostLocal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="monthlyCostUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="oneTimeCostUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="localCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="coverageIndicator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="supplierService" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="accessBandwidth" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="tailTechnology" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="technology" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Serial_Number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Expiration_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="accessInterconnect" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Caveat_Ids" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="providerProductCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="providerProductName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="upStreamSpeed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="downStreamSpeed" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="orderingCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="accessType" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="bestPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nodeObj"
})
@XmlRootElement(name = "nodeList")
public class NodeList {

    protected List<NodeList.NodeObj> nodeObj;

    /**
     * Gets the value of the nodeObj property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nodeObj property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNodeObj().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NodeList.NodeObj }
     * 
     * 
     */
    public List<NodeList.NodeObj> getNodeObj() {
        if (nodeObj == null) {
            nodeObj = new ArrayList<NodeList.NodeObj>();
        }
        return this.nodeObj;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="nodeName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="CLLI" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="signalType" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element ref="{http://edb.att.com/accessQuote}contractTermList"/>
     *         &lt;element name="monthlyCostLocal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="oneTimeCostLocal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="monthlyCostUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="oneTimeCostUSD" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="localCurrency" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="coverageIndicator" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="supplierService" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="accessBandwidth" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="tailTechnology" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="technology" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Serial_Number" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Expiration_date" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="accessInterconnect" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Caveat_Ids" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="notes" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="providerProductCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="providerProductName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="upStreamSpeed" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="downStreamSpeed" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="orderingCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="accessType" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="bestPrice" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nodeName",
        "clli",
        "address",
        "signalType",
        "contractTermList",
        "monthlyCostLocal",
        "oneTimeCostLocal",
        "monthlyCostUSD",
        "oneTimeCostUSD",
        "localCurrency",
        "coverageIndicator",
        "supplierService",
        "accessBandwidth",
        "tailTechnology",
        "technology",
        "serialNumber",
        "expirationDate",
        "accessInterconnect",
        "caveatIds",
        "notes",
        "providerProductCode",
        "providerProductName",
        "upStreamSpeed",
        "downStreamSpeed",
        "orderingCode",
        "accessType",
        "bestPrice"
    })
    public static class NodeObj {

        @XmlElement(required = true)
        protected String nodeName;
        @XmlElement(name = "CLLI", required = true)
        protected String clli;
        @XmlElement(required = true)
        protected String address;
        protected int signalType;
        @XmlElement(required = true)
        protected ContractTermList contractTermList;
        @XmlElement(required = true)
        protected BigDecimal monthlyCostLocal;
        @XmlElement(required = true)
        protected BigDecimal oneTimeCostLocal;
        @XmlElement(required = true)
        protected BigDecimal monthlyCostUSD;
        @XmlElement(required = true)
        protected BigDecimal oneTimeCostUSD;
        @XmlElement(required = true)
        protected String localCurrency;
        @XmlElement(required = true)
        protected String coverageIndicator;
        @XmlElement(required = true)
        protected String supplierService;
        protected int accessBandwidth;
        protected int tailTechnology;
        @XmlElement(required = true)
        protected String technology;
        @XmlElement(name = "Serial_Number", required = true)
        protected String serialNumber;
        @XmlElement(name = "Expiration_date", required = true)
        protected String expirationDate;
        protected int accessInterconnect;
        @XmlElement(name = "Caveat_Ids", required = true)
        protected String caveatIds;
        @XmlElement(required = true)
        protected String notes;
        @XmlElement(required = true)
        protected String providerProductCode;
        @XmlElement(required = true)
        protected String providerProductName;
        protected int upStreamSpeed;
        protected int downStreamSpeed;
        @XmlElement(required = true)
        protected String orderingCode;
        protected int accessType;
        @XmlElement(required = true)
        protected String bestPrice;

        /**
         * Gets the value of the nodeName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNodeName() {
            return nodeName;
        }

        /**
         * Sets the value of the nodeName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNodeName(String value) {
            this.nodeName = value;
        }

        /**
         * Gets the value of the clli property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCLLI() {
            return clli;
        }

        /**
         * Sets the value of the clli property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCLLI(String value) {
            this.clli = value;
        }

        /**
         * Gets the value of the address property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAddress() {
            return address;
        }

        /**
         * Sets the value of the address property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAddress(String value) {
            this.address = value;
        }

        /**
         * Gets the value of the signalType property.
         * 
         */
        public int getSignalType() {
            return signalType;
        }

        /**
         * Sets the value of the signalType property.
         * 
         */
        public void setSignalType(int value) {
            this.signalType = value;
        }

        /**
         * Gets the value of the contractTermList property.
         * 
         * @return
         *     possible object is
         *     {@link ContractTermList }
         *     
         */
        public ContractTermList getContractTermList() {
            return contractTermList;
        }

        /**
         * Sets the value of the contractTermList property.
         * 
         * @param value
         *     allowed object is
         *     {@link ContractTermList }
         *     
         */
        public void setContractTermList(ContractTermList value) {
            this.contractTermList = value;
        }

        /**
         * Gets the value of the monthlyCostLocal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMonthlyCostLocal() {
            return monthlyCostLocal;
        }

        /**
         * Sets the value of the monthlyCostLocal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMonthlyCostLocal(BigDecimal value) {
            this.monthlyCostLocal = value;
        }

        /**
         * Gets the value of the oneTimeCostLocal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getOneTimeCostLocal() {
            return oneTimeCostLocal;
        }

        /**
         * Sets the value of the oneTimeCostLocal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setOneTimeCostLocal(BigDecimal value) {
            this.oneTimeCostLocal = value;
        }

        /**
         * Gets the value of the monthlyCostUSD property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getMonthlyCostUSD() {
            return monthlyCostUSD;
        }

        /**
         * Sets the value of the monthlyCostUSD property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setMonthlyCostUSD(BigDecimal value) {
            this.monthlyCostUSD = value;
        }

        /**
         * Gets the value of the oneTimeCostUSD property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getOneTimeCostUSD() {
            return oneTimeCostUSD;
        }

        /**
         * Sets the value of the oneTimeCostUSD property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setOneTimeCostUSD(BigDecimal value) {
            this.oneTimeCostUSD = value;
        }

        /**
         * Gets the value of the localCurrency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocalCurrency() {
            return localCurrency;
        }

        /**
         * Sets the value of the localCurrency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocalCurrency(String value) {
            this.localCurrency = value;
        }

        /**
         * Gets the value of the coverageIndicator property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCoverageIndicator() {
            return coverageIndicator;
        }

        /**
         * Sets the value of the coverageIndicator property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCoverageIndicator(String value) {
            this.coverageIndicator = value;
        }

        /**
         * Gets the value of the supplierService property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSupplierService() {
            return supplierService;
        }

        /**
         * Sets the value of the supplierService property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSupplierService(String value) {
            this.supplierService = value;
        }

        /**
         * Gets the value of the accessBandwidth property.
         * 
         */
        public int getAccessBandwidth() {
            return accessBandwidth;
        }

        /**
         * Sets the value of the accessBandwidth property.
         * 
         */
        public void setAccessBandwidth(int value) {
            this.accessBandwidth = value;
        }

        /**
         * Gets the value of the tailTechnology property.
         * 
         */
        public int getTailTechnology() {
            return tailTechnology;
        }

        /**
         * Sets the value of the tailTechnology property.
         * 
         */
        public void setTailTechnology(int value) {
            this.tailTechnology = value;
        }

        /**
         * Gets the value of the technology property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTechnology() {
            return technology;
        }

        /**
         * Sets the value of the technology property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTechnology(String value) {
            this.technology = value;
        }

        /**
         * Gets the value of the serialNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSerialNumber() {
            return serialNumber;
        }

        /**
         * Sets the value of the serialNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSerialNumber(String value) {
            this.serialNumber = value;
        }

        /**
         * Gets the value of the expirationDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExpirationDate() {
            return expirationDate;
        }

        /**
         * Sets the value of the expirationDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExpirationDate(String value) {
            this.expirationDate = value;
        }

        /**
         * Gets the value of the accessInterconnect property.
         * 
         */
        public int getAccessInterconnect() {
            return accessInterconnect;
        }

        /**
         * Sets the value of the accessInterconnect property.
         * 
         */
        public void setAccessInterconnect(int value) {
            this.accessInterconnect = value;
        }

        /**
         * Gets the value of the caveatIds property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCaveatIds() {
            return caveatIds;
        }

        /**
         * Sets the value of the caveatIds property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCaveatIds(String value) {
            this.caveatIds = value;
        }

        /**
         * Gets the value of the notes property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNotes() {
            return notes;
        }

        /**
         * Sets the value of the notes property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNotes(String value) {
            this.notes = value;
        }

        /**
         * Gets the value of the providerProductCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProviderProductCode() {
            return providerProductCode;
        }

        /**
         * Sets the value of the providerProductCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProviderProductCode(String value) {
            this.providerProductCode = value;
        }

        /**
         * Gets the value of the providerProductName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProviderProductName() {
            return providerProductName;
        }

        /**
         * Sets the value of the providerProductName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProviderProductName(String value) {
            this.providerProductName = value;
        }

        /**
         * Gets the value of the upStreamSpeed property.
         * 
         */
        public int getUpStreamSpeed() {
            return upStreamSpeed;
        }

        /**
         * Sets the value of the upStreamSpeed property.
         * 
         */
        public void setUpStreamSpeed(int value) {
            this.upStreamSpeed = value;
        }

        /**
         * Gets the value of the downStreamSpeed property.
         * 
         */
        public int getDownStreamSpeed() {
            return downStreamSpeed;
        }

        /**
         * Sets the value of the downStreamSpeed property.
         * 
         */
        public void setDownStreamSpeed(int value) {
            this.downStreamSpeed = value;
        }

        /**
         * Gets the value of the orderingCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrderingCode() {
            return orderingCode;
        }

        /**
         * Sets the value of the orderingCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrderingCode(String value) {
            this.orderingCode = value;
        }

        /**
         * Gets the value of the accessType property.
         * 
         */
        public int getAccessType() {
            return accessType;
        }

        /**
         * Sets the value of the accessType property.
         * 
         */
        public void setAccessType(int value) {
            this.accessType = value;
        }

        /**
         * Gets the value of the bestPrice property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBestPrice() {
            return bestPrice;
        }

        /**
         * Sets the value of the bestPrice property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBestPrice(String value) {
            this.bestPrice = value;
        }

    }

}
