//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.31 at 10:39:18 AM EST 
//


package com.att.edb.accessquote;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.att.edb.accessquote package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.att.edb.accessquote
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AccessQuoteAlternateResponse.AccessQuoteAlternateBody.AccessSupplierList.AccessSupplier }
     * 
     */
    public AccessQuoteAlternateResponse.AccessQuoteAlternateBody.AccessSupplierList.AccessSupplier createAccessQuoteAlternateResponseAccessQuoteAlternateBodyAccessSupplierListAccessSupplier() {
        return new AccessQuoteAlternateResponse.AccessQuoteAlternateBody.AccessSupplierList.AccessSupplier();
    }

    /**
     * Create an instance of {@link GetAccessQuoteAlternate }
     * 
     */
    public GetAccessQuoteAlternate createGetAccessQuoteAlternate() {
        return new GetAccessQuoteAlternate();
    }

    /**
     * Create an instance of {@link InterfaceList }
     * 
     */
    public InterfaceList createInterfaceList() {
        return new InterfaceList();
    }

    /**
     * Create an instance of {@link AccessQuoteAlternateResponse.AccessQuoteAlternateBody.AccessSupplierList }
     * 
     */
    public AccessQuoteAlternateResponse.AccessQuoteAlternateBody.AccessSupplierList createAccessQuoteAlternateResponseAccessQuoteAlternateBodyAccessSupplierList() {
        return new AccessQuoteAlternateResponse.AccessQuoteAlternateBody.AccessSupplierList();
    }

    /**
     * Create an instance of {@link AltNodeList }
     * 
     */
    public AltNodeList createAltNodeList() {
        return new AltNodeList();
    }

    /**
     * Create an instance of {@link AccessQuoteAlternateRequest }
     * 
     */
    public AccessQuoteAlternateRequest createAccessQuoteAlternateRequest() {
        return new AccessQuoteAlternateRequest();
    }

    /**
     * Create an instance of {@link NodeList }
     * 
     */
    public NodeList createNodeList() {
        return new NodeList();
    }

    /**
     * Create an instance of {@link AccessQuoteAlternateResponse }
     * 
     */
    public AccessQuoteAlternateResponse createAccessQuoteAlternateResponse() {
        return new AccessQuoteAlternateResponse();
    }

    /**
     * Create an instance of {@link AltInterfaceList }
     * 
     */
    public AltInterfaceList createAltInterfaceList() {
        return new AltInterfaceList();
    }

    /**
     * Create an instance of {@link AccessQuoteAlternateResponse.AccessQuoteAlternateBody }
     * 
     */
    public AccessQuoteAlternateResponse.AccessQuoteAlternateBody createAccessQuoteAlternateResponseAccessQuoteAlternateBody() {
        return new AccessQuoteAlternateResponse.AccessQuoteAlternateBody();
    }

    /**
     * Create an instance of {@link AccessQuoteRequest }
     * 
     */
    public AccessQuoteRequest createAccessQuoteRequest() {
        return new AccessQuoteRequest();
    }

    /**
     * Create an instance of {@link AltContractTermList.ContractTermObj }
     * 
     */
    public AltContractTermList.ContractTermObj createAltContractTermListContractTermObj() {
        return new AltContractTermList.ContractTermObj();
    }

    /**
     * Create an instance of {@link NodeList.NodeObj }
     * 
     */
    public NodeList.NodeObj createNodeListNodeObj() {
        return new NodeList.NodeObj();
    }

    /**
     * Create an instance of {@link GetAccessQuoteAlternateResponse }
     * 
     */
    public GetAccessQuoteAlternateResponse createGetAccessQuoteAlternateResponse() {
        return new GetAccessQuoteAlternateResponse();
    }

    /**
     * Create an instance of {@link AccessQuoteResponse.AccessQuoteBody.AccessSupplierList.AccessSupplier }
     * 
     */
    public AccessQuoteResponse.AccessQuoteBody.AccessSupplierList.AccessSupplier createAccessQuoteResponseAccessQuoteBodyAccessSupplierListAccessSupplier() {
        return new AccessQuoteResponse.AccessQuoteBody.AccessSupplierList.AccessSupplier();
    }

    /**
     * Create an instance of {@link AltNodeList.NodeObj }
     * 
     */
    public AltNodeList.NodeObj createAltNodeListNodeObj() {
        return new AltNodeList.NodeObj();
    }

    /**
     * Create an instance of {@link GetAccessQuote }
     * 
     */
    public GetAccessQuote createGetAccessQuote() {
        return new GetAccessQuote();
    }

    /**
     * Create an instance of {@link ContractTermList.ContractTermObj }
     * 
     */
    public ContractTermList.ContractTermObj createContractTermListContractTermObj() {
        return new ContractTermList.ContractTermObj();
    }

    /**
     * Create an instance of {@link InterfaceList.InterfaceObj }
     * 
     */
    public InterfaceList.InterfaceObj createInterfaceListInterfaceObj() {
        return new InterfaceList.InterfaceObj();
    }

    /**
     * Create an instance of {@link AltContractTermList }
     * 
     */
    public AltContractTermList createAltContractTermList() {
        return new AltContractTermList();
    }

    /**
     * Create an instance of {@link AccessQuoteAlternateRequest.AccessQuoteAlternateBody }
     * 
     */
    public AccessQuoteAlternateRequest.AccessQuoteAlternateBody createAccessQuoteAlternateRequestAccessQuoteAlternateBody() {
        return new AccessQuoteAlternateRequest.AccessQuoteAlternateBody();
    }

    /**
     * Create an instance of {@link AccessQuoteResponse }
     * 
     */
    public AccessQuoteResponse createAccessQuoteResponse() {
        return new AccessQuoteResponse();
    }

    /**
     * Create an instance of {@link ContractTermList }
     * 
     */
    public ContractTermList createContractTermList() {
        return new ContractTermList();
    }

    /**
     * Create an instance of {@link GetAccessQuoteResponse }
     * 
     */
    public GetAccessQuoteResponse createGetAccessQuoteResponse() {
        return new GetAccessQuoteResponse();
    }

    /**
     * Create an instance of {@link AltInterfaceList.InterfaceObj }
     * 
     */
    public AltInterfaceList.InterfaceObj createAltInterfaceListInterfaceObj() {
        return new AltInterfaceList.InterfaceObj();
    }

    /**
     * Create an instance of {@link AccessQuoteResponse.AccessQuoteBody.AccessSupplierList }
     * 
     */
    public AccessQuoteResponse.AccessQuoteBody.AccessSupplierList createAccessQuoteResponseAccessQuoteBodyAccessSupplierList() {
        return new AccessQuoteResponse.AccessQuoteBody.AccessSupplierList();
    }

    /**
     * Create an instance of {@link AccessQuoteResponse.AccessQuoteBody }
     * 
     */
    public AccessQuoteResponse.AccessQuoteBody createAccessQuoteResponseAccessQuoteBody() {
        return new AccessQuoteResponse.AccessQuoteBody();
    }

    /**
     * Create an instance of {@link AccessQuoteRequest.AccessQuoteBody }
     * 
     */
    public AccessQuoteRequest.AccessQuoteBody createAccessQuoteRequestAccessQuoteBody() {
        return new AccessQuoteRequest.AccessQuoteBody();
    }

}
