//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.31 at 12:18:30 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://edb.att.com/accessQuote", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.att.edb.accessquote;
