CREATE TABLE SLEXP_SITE_CONFIG
(
  ID INTEGER PRIMARY KEY,
  SITE_NAME VARCHAR2(120),
  SITE_DATA CLOB
)

CREATE TABLE SLEXP_USER_DETAIL
(
  ID INTEGER PRIMARY KEY,
  USER_ID VARCHAR2(8),
  SITE_DATA CLOB,
  SOLUTION_ID INTEGER,
  SITE_ID INTEGER,
  SITE_ADDR VARCHAR2(60)
 )

 CREATE TABLE SLEXP_SITEDETAIL_TX
(
  ID INTEGER PRIMARY KEY,
  SITE_ID INTEGER,
  ACCESS_DATA CLOB,
  USER_ID VARCHAR2(8),
  SERVICE_FEATURE_DATA CLOB,
  SOLUTION_ID INTEGER
)

CREATE TABLE SLEXP_SERVICE_CONFIG
(
  SERVICE_ID INTEGER PRIMARY KEY,
  SERVICE_NAME VARCHAR2(20) NOT NULL,
  CREATED_DATE DATE NOT NULL
)

CREATE TABLE SLEXP_RESULTS_REF
(
  RESULT_ID INTEGER PRIMARY KEY,
  PRODUCT_ID VARCHAR2(50),
  MRC INTEGER,
  NRC INTEGER,
  ACCESS_SPEED VARCHAR2(50),
  PORT_SPEED VARCHAR2(50),
  CREATED_DATE DATE
)

CREATE SEQUENCE SLEXP_SITEDETAIL_TX_SEQ
  MINVALUE 1
  START WITH 1
  INCREMENT BY 1
  CACHE 20;
  
  --------------------------------------------------------
--  File created - Friday-January-13-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table SLEXP_RESULTS_REF
--------------------------------------------------------

  CREATE TABLE "ADOPT_SB1"."SLEXP_RESULTS_REF" ("RESULT_ID" NUMBER(*,0), "PRODUCT_ID" VARCHAR2(50), "MRC" NUMBER(*,0), "NRC" NUMBER(*,0), "ACCESS_SPEED" VARCHAR2(50), "PORT_SPEED" VARCHAR2(50), "CREATED_DATE" DATE)
--------------------------------------------------------
--  DDL for Table SLEXP_SERVICE_CONFIG
--------------------------------------------------------

  CREATE TABLE "ADOPT_SB1"."SLEXP_SERVICE_CONFIG" ("SERVICE_ID" NUMBER(*,0), "SERVICE_NAME" VARCHAR2(20), "CREATED_DATE" DATE)
--------------------------------------------------------
--  DDL for Table SLEXP_SITE_CONFIG
--------------------------------------------------------

  CREATE TABLE "ADOPT_SB1"."SLEXP_SITE_CONFIG" ("ID" NUMBER(*,0), "SITE_NAME" VARCHAR2(120), "SITE_DATA" CLOB, "TEST_SITE_METADATA" CLOB)
--------------------------------------------------------
--  DDL for Table SLEXP_SITEDETAIL_TX
--------------------------------------------------------

  CREATE TABLE "ADOPT_SB1"."SLEXP_SITEDETAIL_TX" ("ID" NUMBER(*,0), "SITE_ID" NUMBER(*,0), "ACCESS_DATA" CLOB, "USER_ID" VARCHAR2(8), "SERVICE_FEATURE_DATA" CLOB, "SOLUTION_ID" NUMBER(*,0))
--------------------------------------------------------
--  DDL for Table SLEXP_USER_DETAIL
--------------------------------------------------------

  CREATE TABLE "ADOPT_SB1"."SLEXP_USER_DETAIL" ("ID" NUMBER(*,0), "USER_ID" VARCHAR2(8), "SITE_DATA" CLOB, "SOLUTION_ID" NUMBER(*,0), "SITE_ID" NUMBER(*,0), "SITE_ADDR" VARCHAR2(60))
REM INSERTING into ADOPT_SB1.SLEXP_RESULTS_REF
SET DEFINE OFF;
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (2,'VPN Value Bundle',1150,1000,'1.8G','1.5G',to_date('27-DEC-16','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (3,'VPN Value Bundle',1190,1011,'1.0G','0.9G',to_date('27-DEC-16','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (4,'VPN Value Bundle',1190,1011,'6M','5M',to_date('28-DEC-16','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (5,'VPN Value Bundle',1700,1011,'6M','5M',to_date('28-DEC-16','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (7,'AVPN Express',1500,1011,'6M','4M',to_date('28-DEC-16','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (1,'VPN Value Bundle',100,110,'1.1G','60M',to_date('27-DEC-16','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (8,'AVPN Express',1600,1200,'1.1G','60M',to_date('27-DEC-16','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (9,'FBB Express',999,799,'1.1G','60M',to_date('27-DEC-16','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (10,'VPN Value Bundle',50,150,'1M','1M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (11,'AVPN Express',150,200,'1M','3M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (12,'FBB Express',250,300,'1M','4M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (13,'Standalone AVPN',350,400,'1M','5M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (14,'VPN Value Bundle',75,175,'2M','1M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (15,'AVPN Express',100,200,'2M','2M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (16,'FBB Express',150,175,'2M','3M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (17,'Standalone AVPN',175,225,'2M','4M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (18,'Managed Internet Service',200,250,'2M','5M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (19,'VPN Value Bundle',90,175,'3M','1M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (20,'AVPN Express',125,225,'3M','2M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (21,'FBB Express',150,250,'3M','3M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (22,'Standalone AVPN',175,275,'3M','4M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (23,'Managed Internet Service',190,280,'3M','5M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (24,'VPN Value Bundle',50,150,'4M','1M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (25,'AVPN Express',125,175,'4M','2M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (26,'FBB Express',145,225,'4M','3M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (27,'Standalone AVPN',160,260,'4M','4M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (28,'Managed Internet Service',225,275,'4M','5M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (29,'VPN Value Bundle',50,150,'5M','1M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (30,'AVPN Express',225,325,'5M','2M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (31,'FBB Express',85,185,'5M','3M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (32,'Standalone AVPN',125,225,'5M','4M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (33,'Managed Internet Service',225,275,'5M','5M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (34,'VPN Value Bundle',50,150,'1M','2M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (35,'AVPN Express',1000,1200,'10G','10G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (36,'FBB Express',1100,1300,'10G','20G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (37,'Standalone AVPN',1200,1300,'10G','30G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (38,'Standalone AVPN',1300,1400,'10G','40G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (39,'Standalone AVPN',1400,1500,'10G','50G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (40,'VPN Value Bundle',1500,1600,'20G','10G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (41,'AVPN Express',1600,1700,'20G','20G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (42,'FBB Express',1700,1800,'20G','30G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (43,'Standalone AVPN',1800,1900,'20G','40G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (44,'Managed Internet Service',1900,2000,'20G','50G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (45,'VPN Value Bundle',2000,2100,'30G','10G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (46,'AVPN Express',2100,2200,'30G','20G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (47,'FBB Express',2200,2300,'30G','30G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (48,'Standalone AVPN',2300,2400,'30G','40G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (49,'Managed Internet Service',2400,2500,'30G','50G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (50,'VPN Value Bundle',2600,2700,'40G','10G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (51,'AVPN Express',2700,2800,'40G','20G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (52,'FBB Express',2800,2900,'40G','30G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (53,'Standalone AVPN',3000,3100,'40G','40G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (54,'Managed Internet Service',3100,3200,'40G','50G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (55,'VPN Value Bundle',2350,2450,'50G','10G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (56,'AVPN Express',2450,2550,'50G','20G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (57,'FBB Express',2550,2650,'50G','30G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (58,'Standalone AVPN',2650,2750,'50G','40G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (59,'Managed Internet Service',2750,2850,'50G','50G',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (60,'AVPN Express',3000,3200,'100M','100M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (61,'FBB Express',3100,32500,'100M','200M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (62,'Standalone AVPN',3250,3300,'100M','300M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (63,'Standalone AVPN',3300,3400,'100M','400M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (64,'Standalone AVPN',3400,3500,'100M','500M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (65,'VPN Value Bundle',3500,3600,'200M','100M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (66,'AVPN Express',3600,3700,'200M','200M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (67,'FBB Express',3700,3800,'200M','300M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (68,'Standalone AVPN',3800,3900,'200M','400M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (69,'Managed Internet Service',3900,4000,'200M','500M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (70,'VPN Value Bundle',4000,4100,'300M','100M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (71,'AVPN Express',4100,4200,'300M','200M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (72,'FBB Express',4200,4300,'300M','300M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (73,'Standalone AVPN',4300,4400,'300M','400M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (74,'Managed Internet Service',4400,4500,'300M','500M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (75,'VPN Value Bundle',5600,5700,'400M','100M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (76,'AVPN Express',5700,5800,'400M','200M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (77,'FBB Express',5800,5900,'400M','300M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (78,'Standalone AVPN',5000,5100,'400M','400M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (79,'Managed Internet Service',5100,5200,'400M','500M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (80,'VPN Value Bundle',4350,5450,'500M','100M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (81,'AVPN Express',5450,5550,'500M','200M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (82,'FBB Express',5550,5650,'500M','300M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (83,'Standalone AVPN',5650,5750,'500M','400M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (84,'Managed Internet Service',5750,5850,'500M','500M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (85,'VPN Value Bundle',4450,5550,'500M','100M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (86,'AVPN Express',5550,5650,'500M','200M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (87,'FBB Express',5650,5750,'500M','300M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (88,'Standalone AVPN',5750,5850,'500M','400M',to_date('11-JAN-17','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_RESULTS_REF (RESULT_ID,PRODUCT_ID,MRC,NRC,ACCESS_SPEED,PORT_SPEED,CREATED_DATE) values (89,'Managed Internet Service',5850,5950,'500M','500M',to_date('11-JAN-17','DD-MON-RR'));
REM INSERTING into ADOPT_SB1.SLEXP_SERVICE_CONFIG
SET DEFINE OFF;
Insert into ADOPT_SB1.SLEXP_SERVICE_CONFIG (SERVICE_ID,SERVICE_NAME,CREATED_DATE) values (1,'Data',to_date('28-DEC-16','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_SERVICE_CONFIG (SERVICE_ID,SERVICE_NAME,CREATED_DATE) values (2,'Voice',to_date('28-DEC-16','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_SERVICE_CONFIG (SERVICE_ID,SERVICE_NAME,CREATED_DATE) values (3,'Security Services',to_date('28-DEC-16','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_SERVICE_CONFIG (SERVICE_ID,SERVICE_NAME,CREATED_DATE) values (4,'Misc',to_date('28-DEC-16','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_SERVICE_CONFIG (SERVICE_ID,SERVICE_NAME,CREATED_DATE) values (5,'Hosting',to_date('28-DEC-16','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_SERVICE_CONFIG (SERVICE_ID,SERVICE_NAME,CREATED_DATE) values (6,'Cloud',to_date('28-DEC-16','DD-MON-RR'));
Insert into ADOPT_SB1.SLEXP_SERVICE_CONFIG (SERVICE_ID,SERVICE_NAME,CREATED_DATE) values (7,'Entertainment',to_date('28-DEC-16','DD-MON-RR'));
REM INSERTING into ADOPT_SB1.SLEXP_SITE_CONFIG
SET DEFINE OFF;
Insert into ADOPT_SB1.SLEXP_SITE_CONFIG (ID,SITE_NAME) values (1,'testSite');
REM INSERTING into ADOPT_SB1.SLEXP_SITEDETAIL_TX
SET DEFINE OFF;
Insert into ADOPT_SB1.SLEXP_SITEDETAIL_TX (ID,SITE_ID,USER_ID,SOLUTION_ID) values (26,1,'vg8736',300001);
Insert into ADOPT_SB1.SLEXP_SITEDETAIL_TX (ID,SITE_ID,USER_ID,SOLUTION_ID) values (25,1,'vg8736',100001);
REM INSERTING into ADOPT_SB1.SLEXP_USER_DETAIL
SET DEFINE OFF;
Insert into ADOPT_SB1.SLEXP_USER_DETAIL (ID,USER_ID,SOLUTION_ID,SITE_ID,SITE_ADDR) values (1,'vg8736',100001,2,'9804 Camden Hills Avenue, Las Vegas, NV 89145 US');
Insert into ADOPT_SB1.SLEXP_USER_DETAIL (ID,USER_ID,SOLUTION_ID,SITE_ID,SITE_ADDR) values (2,'sw088d',200001,3,'1 Erieview Plaza, Suite 1300, Cleveland, Ohio 44114');
Insert into ADOPT_SB1.SLEXP_USER_DETAIL (ID,USER_ID,SOLUTION_ID,SITE_ID,SITE_ADDR) values (5,'sw088d',200002,8,'Flushing Meadow - Corona Park, Flushing, NY 11368');
Insert into ADOPT_SB1.SLEXP_USER_DETAIL (ID,USER_ID,SOLUTION_ID,SITE_ID,SITE_ADDR) values (4,'vg8736',100002,1,'Flushing Meadow - Corona Park, Flushing, NY 11368');
--------------------------------------------------------
--  DDL for Index SYS_C00305290
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADOPT_SB1"."SYS_C00305290" ON "ADOPT_SB1"."SLEXP_RESULTS_REF" ("RESULT_ID")
--------------------------------------------------------
--  DDL for Index SYS_C00305289
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADOPT_SB1"."SYS_C00305289" ON "ADOPT_SB1"."SLEXP_SERVICE_CONFIG" ("SERVICE_ID")
--------------------------------------------------------
--  DDL for Index SYS_C00305284
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADOPT_SB1"."SYS_C00305284" ON "ADOPT_SB1"."SLEXP_SITE_CONFIG" ("ID")
--------------------------------------------------------
--  DDL for Index SYS_C00305292
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADOPT_SB1"."SYS_C00305292" ON "ADOPT_SB1"."SLEXP_SITEDETAIL_TX" ("ID")
--------------------------------------------------------
--  DDL for Index SYS_C00305285
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADOPT_SB1"."SYS_C00305285" ON "ADOPT_SB1"."SLEXP_USER_DETAIL" ("ID")
--------------------------------------------------------
--  Constraints for Table SLEXP_RESULTS_REF
--------------------------------------------------------

  ALTER TABLE "ADOPT_SB1"."SLEXP_RESULTS_REF" ADD PRIMARY KEY ("RESULT_ID") USING INDEX  ENABLE
--------------------------------------------------------
--  Constraints for Table SLEXP_SERVICE_CONFIG
--------------------------------------------------------

  ALTER TABLE "ADOPT_SB1"."SLEXP_SERVICE_CONFIG" ADD PRIMARY KEY ("SERVICE_ID") USING INDEX  ENABLE
  ALTER TABLE "ADOPT_SB1"."SLEXP_SERVICE_CONFIG" MODIFY ("CREATED_DATE" NOT NULL ENABLE)
  ALTER TABLE "ADOPT_SB1"."SLEXP_SERVICE_CONFIG" MODIFY ("SERVICE_NAME" NOT NULL ENABLE)
--------------------------------------------------------
--  Constraints for Table SLEXP_SITE_CONFIG
--------------------------------------------------------

  ALTER TABLE "ADOPT_SB1"."SLEXP_SITE_CONFIG" ADD PRIMARY KEY ("ID") USING INDEX  ENABLE
--------------------------------------------------------
--  Constraints for Table SLEXP_SITEDETAIL_TX
--------------------------------------------------------

  ALTER TABLE "ADOPT_SB1"."SLEXP_SITEDETAIL_TX" ADD PRIMARY KEY ("ID") USING INDEX  ENABLE
--------------------------------------------------------
--  Constraints for Table SLEXP_USER_DETAIL
--------------------------------------------------------

  ALTER TABLE "ADOPT_SB1"."SLEXP_USER_DETAIL" ADD PRIMARY KEY ("ID") USING INDEX  ENABLE
