//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.30 at 06:15:54 PM EST 
//


package com.att.cio.commonheader.v3;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.att.cio.commonheader.v3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WSCorrelationId_QNAME = new QName("http://cio.att.com/commonheader/v3", "WSCorrelationId");
    private final static QName _WSResponseMessageExpiration_QNAME = new QName("http://cio.att.com/commonheader/v3", "WSResponseMessageExpiration");
    private final static QName _WSConversationId_QNAME = new QName("http://cio.att.com/commonheader/v3", "WSConversationId");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.att.cio.commonheader.v3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WSEndUserToken }
     * 
     */
    public WSEndUserToken createWSEndUserToken() {
        return new WSEndUserToken();
    }

    /**
     * Create an instance of {@link WSContext }
     * 
     */
    public WSContext createWSContext() {
        return new WSContext();
    }

    /**
     * Create an instance of {@link WSCallback }
     * 
     */
    public WSCallback createWSCallback() {
        return new WSCallback();
    }

    /**
     * Create an instance of {@link WSContext.WSNameValue }
     * 
     */
    public WSContext.WSNameValue createWSContextWSNameValue() {
        return new WSContext.WSNameValue();
    }

    /**
     * Create an instance of {@link WSNameValueType }
     * 
     */
    public WSNameValueType createWSNameValueType() {
        return new WSNameValueType();
    }

    /**
     * Create an instance of {@link WSException }
     * 
     */
    public WSException createWSException() {
        return new WSException();
    }

    /**
     * Create an instance of {@link WSHeader }
     * 
     */
    public WSHeader createWSHeader() {
        return new WSHeader();
    }

    /**
     * Create an instance of {@link WSEnterpriseLogging }
     * 
     */
    public WSEnterpriseLogging createWSEnterpriseLogging() {
        return new WSEnterpriseLogging();
    }

    /**
     * Create an instance of {@link WSContext.Version }
     * 
     */
    public WSContext.Version createWSContextVersion() {
        return new WSContext.Version();
    }

    /**
     * Create an instance of {@link WSResponseHeader }
     * 
     */
    public WSResponseHeader createWSResponseHeader() {
        return new WSResponseHeader();
    }

    /**
     * Create an instance of {@link WSMessageData }
     * 
     */
    public WSMessageData createWSMessageData() {
        return new WSMessageData();
    }

    /**
     * Create an instance of {@link WSException.AdditionalErrors }
     * 
     */
    public WSException.AdditionalErrors createWSExceptionAdditionalErrors() {
        return new WSException.AdditionalErrors();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cio.att.com/commonheader/v3", name = "WSCorrelationId")
    public JAXBElement<String> createWSCorrelationId(String value) {
        return new JAXBElement<String>(_WSCorrelationId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cio.att.com/commonheader/v3", name = "WSResponseMessageExpiration")
    public JAXBElement<Long> createWSResponseMessageExpiration(Long value) {
        return new JAXBElement<Long>(_WSResponseMessageExpiration_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://cio.att.com/commonheader/v3", name = "WSConversationId")
    public JAXBElement<String> createWSConversationId(String value) {
        return new JAXBElement<String>(_WSConversationId_QNAME, String.class, null, value);
    }

}
