//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.31 at 11:55:55 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://cio.att.com/commonheader/v3", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.att.cio.commonheader.v3;
