//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.31 at 10:39:18 AM EST 
//


package com.att.cio.commonheader.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://cio.att.com/commonheader/v3}WSEndUserToken" minOccurs="0"/>
 *         &lt;element ref="{http://cio.att.com/commonheader/v3}WSContext" minOccurs="0"/>
 *         &lt;element ref="{http://cio.att.com/commonheader/v3}WSCallback" minOccurs="0"/>
 *         &lt;element ref="{http://cio.att.com/commonheader/v3}WSConversationId" minOccurs="0"/>
 *         &lt;element ref="{http://cio.att.com/commonheader/v3}WSMessageData" minOccurs="0"/>
 *         &lt;element ref="{http://cio.att.com/commonheader/v3}WSResponseMessageExpiration" minOccurs="0"/>
 *         &lt;element ref="{http://cio.att.com/commonheader/v3}WSEnterpriseLogging" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "wsEndUserToken",
    "wsContext",
    "wsCallback",
    "wsConversationId",
    "wsMessageData",
    "wsResponseMessageExpiration",
    "wsEnterpriseLogging"
})
@XmlRootElement(name = "WSHeader")
public class WSHeader {

    @XmlElement(name = "WSEndUserToken")
    protected WSEndUserToken wsEndUserToken;
    @XmlElement(name = "WSContext")
    protected WSContext wsContext;
    @XmlElement(name = "WSCallback")
    protected WSCallback wsCallback;
    @XmlElement(name = "WSConversationId")
    protected String wsConversationId;
    @XmlElement(name = "WSMessageData")
    protected WSMessageData wsMessageData;
    @XmlElement(name = "WSResponseMessageExpiration")
    protected Long wsResponseMessageExpiration;
    @XmlElement(name = "WSEnterpriseLogging")
    protected WSEnterpriseLogging wsEnterpriseLogging;

    /**
     * Gets the value of the wsEndUserToken property.
     * 
     * @return
     *     possible object is
     *     {@link WSEndUserToken }
     *     
     */
    public WSEndUserToken getWSEndUserToken() {
        return wsEndUserToken;
    }

    /**
     * Sets the value of the wsEndUserToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSEndUserToken }
     *     
     */
    public void setWSEndUserToken(WSEndUserToken value) {
        this.wsEndUserToken = value;
    }

    /**
     * Gets the value of the wsContext property.
     * 
     * @return
     *     possible object is
     *     {@link WSContext }
     *     
     */
    public WSContext getWSContext() {
        return wsContext;
    }

    /**
     * Sets the value of the wsContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSContext }
     *     
     */
    public void setWSContext(WSContext value) {
        this.wsContext = value;
    }

    /**
     * Gets the value of the wsCallback property.
     * 
     * @return
     *     possible object is
     *     {@link WSCallback }
     *     
     */
    public WSCallback getWSCallback() {
        return wsCallback;
    }

    /**
     * Sets the value of the wsCallback property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSCallback }
     *     
     */
    public void setWSCallback(WSCallback value) {
        this.wsCallback = value;
    }

    /**
     * Gets the value of the wsConversationId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWSConversationId() {
        return wsConversationId;
    }

    /**
     * Sets the value of the wsConversationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWSConversationId(String value) {
        this.wsConversationId = value;
    }

    /**
     * Gets the value of the wsMessageData property.
     * 
     * @return
     *     possible object is
     *     {@link WSMessageData }
     *     
     */
    public WSMessageData getWSMessageData() {
        return wsMessageData;
    }

    /**
     * Sets the value of the wsMessageData property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSMessageData }
     *     
     */
    public void setWSMessageData(WSMessageData value) {
        this.wsMessageData = value;
    }

    /**
     * Gets the value of the wsResponseMessageExpiration property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getWSResponseMessageExpiration() {
        return wsResponseMessageExpiration;
    }

    /**
     * Sets the value of the wsResponseMessageExpiration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setWSResponseMessageExpiration(Long value) {
        this.wsResponseMessageExpiration = value;
    }

    /**
     * Gets the value of the wsEnterpriseLogging property.
     * 
     * @return
     *     possible object is
     *     {@link WSEnterpriseLogging }
     *     
     */
    public WSEnterpriseLogging getWSEnterpriseLogging() {
        return wsEnterpriseLogging;
    }

    /**
     * Sets the value of the wsEnterpriseLogging property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSEnterpriseLogging }
     *     
     */
    public void setWSEnterpriseLogging(WSEnterpriseLogging value) {
        this.wsEnterpriseLogging = value;
    }

}
